name: ReportSystem
version: 2.5
main: com.milkd.main.ReportSystem
api-version: 1.13
authors:
  - EricLam
commands:
  report:
    description: report command
  reportadmin:
    description: report admin command
permissions:
  report.helper:
    description: helper permission
  report.mod:
    description: mod permission
  report.admin:
    description: admin permission